# server
server:
  port: 8080
# spring
spring:
  servlet:
    multipart:
      # 限制上传请求的最大值
      max-request-size: 10MB
      # 限制上传文件的做大致
      max-file-size: 10MB
  application:
    name: code-obfuscation
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/code_obfuscation?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

      # 远程服务器销毁 数据库无法使用
      username: code_obfuscation
      password: Ed78zHFkM8X3Jn4p

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
# sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

file:
  # 服务器地址
  uploadUrl: "/home/project/upload/"
  # 本地地址
  localUrl: "D:/Code/Java/upload/files/"

# 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [helath, metrics, mappings, httptrace]




